- name: set up prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: create github runner user
  ansible.builtin.user:
    name: github

- name: create github actions folder
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: github
    group: github

- name: download github runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz
    dest: /actions-runner
    owner: github
    group: github
    remote_src: yes

# - name: Install vault token 
#   ansible.builtin.pip3.11:
#     name: hvac

- name: Configure github runner
  # ansible.builtin.shell: ./config.sh --url https://github.com/Thippareddygari --token {{ lookup('community.hashi_vault.hashi_vault', 'secret=infra/data/github-runner:RUNNER_TOKEN token={{ vault_token }} url=http://vault-internal.kommanuthala.store:8200') }} --unattended
  ansible.builtin.shell: ./config.sh --url https://github.com/Thippareddygari --token {{ lookup('community.hashi_vault.hashi_vault', 'infra/data/github-runner:RUNNER_TOKEN token={{ vault_token }} url=http://vault-internal.rdevopsb83.online:8200') }}
  args:
    chdir: /actions-runner
  become_user: github

